# server version
version: v1.5.4

#server config
server:
  port: ${SERVER_PORT:5001}
  servlet:
    context-path: /WeBASE-Node-Manager


#mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.webank.webase.node.mgr
  mapperLocations: classpath:mapper/*.xml


# database connection configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${WEBASE_DB_IP:127.0.0.1}:${WEBASE_DB_PORT:3306}/${WEBASE_DB_NAME:webasenodemanager}?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: ${WEBASE_DB_UNAME:defaultAccount}
    password: ${WEBASE_DB_PWD:defaultPassword}
    initialSize: 10
    minIdle: 5
    maxActive: 30

  aop:
    proxy-target-class: true

#log config
logging:
  config: classpath:log/log4j2.xml
  level:
    com.webank.webase.node.mgr: info

#constants
constant:
  ###http request
  # login's authorization whether enable, if false, default login as `admin` account
  isUseSecurity: true
  # verification code expire time (s)
  verificationCodeMaxAge: 300
  # if disabled as false, code would be constant value
  enableVerificationCode: true
  # verification code constant value, only when enableVerificationCode is false works
  verificationCodeValue: "8888"
  # auth token code expire time (s)
  authTokenMaxAge: 3600
  ignoreCheckFront: /account/login,/account/pictureCheckCode,/login,/user/privateKey,/front/new,/front/find,,/group/generate,/group/start
  ###front http request
  frontUrl: http://%1s:%2d/WeBASE-Front/%3s
  httpTimeOut: 5000
  contractDeployTimeOut: 30000
  isPrivateKeyEncrypt: true
  maxRequestFail: 3
  sleepWhenHttpMaxFail: 60000

  ###common
  developerModeEnable: true
  deployedModifyEnable: true
  isDeleteInfo: true
  transRetainMax: 10000
  deleteInfoCron: "0 0/1 * * * ?"
  statisticsTransDailyCron: "0 0/1 * * * ?"
  resetGroupListCycle: 600000
  groupInvalidGrayscaleValue: 1M    # y:year, M:month, d:day of month, h:hour, m:minute, n:forever valid
  notSupportFrontIp:

  ###application integration
  # app request timestamp timeout (ms)
  appRequestTimeOut: 300000
  appStatusCheckCycle: 3000

  ###block info (pulling data from chain)
  isBlockPullFromZero: false
  pullBlockInitCnts: 1000
  pullBlockSleepTime: 200
  pullBlockTaskFixedDelay: 30000
  blockRetainMax: 10000
  ###transaction monitor
  transMonitorTaskFixedRate: 60000  #How long does it take to start the next task after the end (second)
  analysisSleepTime: 200
  monitorInfoRetainMax: 10000
  isMonitorIgnoreUser: false
  isMonitorIgnoreContract: false
  monitorUnusualMaxCount: 20
  ###alert mail monitor task interval: 5mins unit: ms
  auditMonitorTaskFixedDelay: 300000
  nodeStatusMonitorTaskFixedDelay: 60000  #must larger than @pullBlockTaskFixedDelay
  certMonitorTaskFixedDelay: 300000
  permitUrlArray: /account/login,/account/pictureCheckCode,/login,/user/privateKey/**,/config/encrypt,/config/version,/front/refresh,/api/*,/config/auth
  ###interval to async refresh group list locally
  resetGroupListInterval: 15000
  ###interval block statistic, unit: ms
  statBlockRetainMax: 100000
  statBlockFixedDelay: 10000
  statBlockPageSize: 20 # block stat data to pull in one time
  enableExternalFromBlock: true # enable record account and contract from block

  #### 1.4.0 visual deploy
  #### deployType 部署方式：
  # 0, 先使用 build_chain.sh 部署链并启用 WeBASE-Front 服务，然后手动添加前置;
  # 1, 使用可视化部署, 需要参考WeBASE文档填写下面参数
  deployType: 0
  #### if deployType = 0, ignore below properties ####
  # 镜像名
  dockerRepository: "fiscoorg/fisco-webase"
  # WeBASE-Sign 访问地址，供节点前置访问，不能填写localhost或127.0.0.1
  webaseSignAddress: "127.0.0.1:5004"
  # 可视化操作的后台超时时间 (unit: ms)，若机器较慢，可动态设置超时时间
  execDockerCheckTimeout: 55000
  execHostCheckTimeout: 55000
  execHostCheckPortTimeout: 50000
  execHostInitTimeout: 300000
  execHostConfigTimeout: 40000
  execBuildChainTimeout: 40000
  dockerRestartPeriodTime: 30000
  execShellTimeout: 600000
  execScpTimeout: 10000
  execAddNodeTimeout: 40000
  # runDockerSleepTime: 600000
  #### if deployType = 0, ignore upper properties ####

sdk:
  # 加密类型：0: 非国密;  1: 国密
  ## 可视化部署时，此配置将决定部署国密或非国密链
  ## 国密与非国密链的私钥、合约数据不兼容
  encryptType: ${ENCRYPT_TYPE:0}

# executor config for async pulling data from chain
executor:
  corePoolSize: 10
  maxPoolSize: 20
  queueSize: 50
  threadNamePrefix: "node-mgr-async-"

# scheduler config for sync scheduled task
scheduler:
  poolSize: 30
  threadNamePrefix: "node-mgr-task-"
  awaitTerminationSeconds: 600
  waitForTasksToCompleteOnShutdown: true

