#server config
server:
  port: 8083
  servlet:
    context-path: /webase-node-mgr


#mybatis config
mybatis:
  typeAliasesPackage: com.webank.webase.node.mgr
  mapperLocations: classpath:mapper/*.xml


# database connection configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/webase_mgr_dev?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

#log config
logging:
  config: classpath:log/log4j2-dev.xml
  level:
    com.webank.webase.node.mgr: debug

#constants
constant:
  blockRetainMax: 10000
  transRetainMax: 10000
  deleteInfoCron: "0 0/2 * * * ?"
  statisticsTransDailyCron: "0 0/1 * * * ?"
  checkNodeStatusCron: "30 0/1 * * * ?"
  insertTransMonitorCron: "0 0/10 * * * ?"
  pullBlockSleepTime: 2000
  resetGroupListCycle: 60000
  isBlockPullFromZero: false
  contractDeployTimeOut: 30000
  httpTimeOut: 5000
  aesKey: ERTadb83f9ege39k
  cookieMaxAge: 1800
  maxRequestFail: 3
  sleepWhenHttpMaxFail: 60000
