# server version
version: v3.0.2

#server config
server:
  port: 6001
#  servlet:
#    context-path: /WeBASE-Node-Manager


spring:
  application:
    # 应用名称
    name: bcos3-node-mgr
  profiles:
    # 环境配置
    active: prod

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: 192.168.1.48:8848
      discovery:
        # 注册组
        group: DEFAULT_GROUP
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: DEFAULT_GROUP
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml
